name: trainers_stopwatch
description: "A new Flutter project."
publish_to: 'none'
version: 0.7.6+13

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  sqflite: ^2.3.3
  path_provider: ^2.1.2
  path: ^1.9.0
  mockito: ^5.4.4
  signals: ^4.5.1
  image_picker: ^1.0.7
  easy_localization: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Regular.ttf
    - family: RedditMono
      fonts:
        - asset: assets/fonts/RedditMono-Regular.ttf
    - family: RedHatMono
      fonts:
        - asset: assets/fonts/RedHatMono-Regular.ttf
  
    - family: StopwatchIcons
      fonts:
        - asset: assets/fonts/StopwatchIcons.ttf
