name: trainers_stopwatch
description: "Multiple Precision Chronometers."
publish_to: 'none'
version: 1.0.6+40

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  mockito: ^5.4.4
  image_picker: ^1.0.7
  easy_localization: ^3.0.5
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  onboarding_overlay: ^3.2.2
  flutter_email_sender: ^6.0.3
  pdf: ^3.11.0
  flutter_colorpicker: ^1.1.0
  flutter_native_splash: ^2.4.1
  share_plus: ^10.0.0
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/stopwatch.png
  min_sdk_android: 21
  adaptive_icon_foreground: assets/icons/stopwatch.png

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

  fonts:
    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Regular.ttf
    - family: RedditMono
      fonts:
        - asset: assets/fonts/RedditMono-Regular.ttf
    - family: RedHatMono
      fonts:
        - asset: assets/fonts/RedHatMono-Regular.ttf
  
    - family: StopwatchIcons
      fonts:
        - asset: assets/fonts/StopwatchIcons.ttf
